nixd: nixt::ASTDeserializer Class Reference
nixt::ASTDeserializer Class Reference
#include <ASTReader.h>
Public Member Functions
ASTDeserializer (DeserializeContext &Ctx, PtrPool< nix::Expr > &Pool, ValueMap &VMap, EnvMap &EMap)
nix::Expr * eatHookable (std::string_view &Data)
nix::Expr * eatNonNullHookable (std::string_view &Data)
template<class T >
T eat (std::string_view &Data)
nix::Symbol eatSymbol (std::string_view &Data)
nix::PosIdx eatPos (std::string_view &Data)
nix::ExprInt eatExprInt (std::string_view &Data)
nix::ExprFloat eatExprFloat (std::string_view &Data)
nix::ExprPath eatExprPath (std::string_view &Data)
nix::ExprVar eatExprVar (nix::PosIdx Pos, std::string_view &Data)
nix::AttrPath eatAttrPath (std::string_view &Data)
nix::ExprSelect eatExprSelect (nix::PosIdx Pos, std::string_view &Data)
nix::ExprOpHasAttr eatExprOpHasAttr (std::string_view &Data)
nix::ExprAttrs eatExprAttrs (nix::PosIdx Pos, std::string_view &Data)
nix::ExprList eatExprList (std::string_view &Data)
nix::ExprLambda eatExprLambnda (nix::PosIdx Pos, std::string_view &Data)
nix::ExprCall eatExprCall (nix::PosIdx Pos, std::string_view &Data)
nix::ExprLet eatExprLet (std::string_view &Data)
nix::ExprWith eatExprWith (nix::PosIdx Pos, std::string_view &Data)
nix::ExprIf eatExprIf (nix::PosIdx Pos, std::string_view &Data)
nix::ExprAssert eatExprAssert (nix::PosIdx Pos, std::string_view &Data)
nix::ExprOpNot eatExprOpNot (std::string_view &Data)
nix::ExprConcatStrings eatExprConcatStrings (nix::PosIdx Pos, std::string_view &Data)
Detailed Description
Definition at line 13 of file ASTReader.h.
Constructor & Destructor Documentation
ASTDeserializer()
nixt::ASTDeserializer::ASTDeserializer (DeserializeContext & Ctx, PtrPool< nix::Expr > & Pool, ValueMap & VMap, EnvMap & EMap) inline
Definition at line 20 of file ASTReader.h.
Member Function Documentation
eat()
template<class T > T nixt::ASTDeserializer::eat (std::string_view & Data) inline
Definition at line 33 of file ASTReader.h.
References bc::eat(), and eat().
Referenced by eat(), eatAttrPath(), eatExprAssert(), eatExprAttrs(), eatExprCall(), eatExprConcatStrings(), eatExprFloat(), eatExprIf(), eatExprInt(), eatExprLambnda(), eatExprLet(), eatExprList(), eatExprOpHasAttr(), eatExprOpNot(), eatExprPath(), eatExprSelect(), eatExprVar(), eatExprWith(), eatHookable(), eatNonNullHookable(), eatPos(), and eatSymbol().
eatAttrPath()
nix::AttrPath nixt::ASTDeserializer::eatAttrPath (std::string_view & Data)
Definition at line 131 of file ASTReader.cpp.
References eat(), eatHookable(), and nixt::DeserializeContext::STable.
Referenced by eatExprOpHasAttr(), and eatExprSelect().
eatExprAssert()
nix::ExprAssert nixt::ASTDeserializer::eatExprAssert (nix::PosIdx Pos, std::string_view & Data)
Definition at line 294 of file ASTReader.cpp.
References eat(), and eatNonNullHookable().
Referenced by eatHookable().
eatExprAttrs()
nix::ExprAttrs nixt::ASTDeserializer::eatExprAttrs (nix::PosIdx Pos, std::string_view & Data)
Definition at line 169 of file ASTReader.cpp.
References eat(), eatHookable(), eatPos(), and eatSymbol().
Referenced by eatHookable().
eatExprCall()
nix::ExprCall nixt::ASTDeserializer::eatExprCall (nix::PosIdx Pos, std::string_view & Data)
Definition at line 253 of file ASTReader.cpp.
References eat(), and eatHookable().
Referenced by eatHookable().
eatExprConcatStrings()
nix::ExprConcatStrings nixt::ASTDeserializer::eatExprConcatStrings (nix::PosIdx Pos, std::string_view & Data)
Definition at line 317 of file ASTReader.cpp.
References eat(), and eatHookable().
Referenced by eatHookable().
eatExprFloat()
nix::ExprFloat nixt::ASTDeserializer::eatExprFloat (std::string_view & Data)
Definition at line 114 of file ASTReader.cpp.
References eat().
Referenced by eatHookable().
eatExprIf()
nix::ExprIf nixt::ASTDeserializer::eatExprIf (nix::PosIdx Pos, std::string_view & Data)
Definition at line 285 of file ASTReader.cpp.
References eat(), and eatNonNullHookable().
Referenced by eatHookable().
eatExprInt()
nix::ExprInt nixt::ASTDeserializer::eatExprInt (std::string_view & Data)
Definition at line 110 of file ASTReader.cpp.
References eat().
Referenced by eatHookable().
eatExprLambnda()
nix::ExprLambda nixt::ASTDeserializer::eatExprLambnda (nix::PosIdx Pos, std::string_view & Data)
Definition at line 214 of file ASTReader.cpp.
References eat(), eatHookable(), eatNonNullHookable(), eatPos(), and eatSymbol().
Referenced by eatHookable().
eatExprLet()
nix::ExprLet nixt::ASTDeserializer::eatExprLet (std::string_view & Data)
Definition at line 269 of file ASTReader.cpp.
References eat(), eatHookable(), eatNonNullHookable(), and nixt::PtrPool< T >::record().
Referenced by eatHookable().
eatExprList()
nix::ExprList nixt::ASTDeserializer::eatExprList (std::string_view & Data)
Definition at line 200 of file ASTReader.cpp.
References eat(), and eatHookable().
Referenced by eatHookable().
eatExprOpHasAttr()
nix::ExprOpHasAttr nixt::ASTDeserializer::eatExprOpHasAttr (std::string_view & Data)
Definition at line 162 of file ASTReader.cpp.
References eat(), eatAttrPath(), and eatHookable().
Referenced by eatHookable().
eatExprOpNot()
nix::ExprOpNot nixt::ASTDeserializer::eatExprOpNot (std::string_view & Data)
Definition at line 302 of file ASTReader.cpp.
References eat(), and eatNonNullHookable().
Referenced by eatHookable().
eatExprPath()
nix::ExprPath nixt::ASTDeserializer::eatExprPath (std::string_view & Data)
Definition at line 118 of file ASTReader.cpp.
References bc::eat(), eat(), and nixt::DeserializeContext::RootFS.
Referenced by eatHookable().
eatExprSelect()
nix::ExprSelect nixt::ASTDeserializer::eatExprSelect (nix::PosIdx Pos, std::string_view & Data)
Definition at line 153 of file ASTReader.cpp.
References eat(), eatAttrPath(), and eatHookable().
Referenced by eatHookable().
eatExprVar()
nix::ExprVar nixt::ASTDeserializer::eatExprVar (nix::PosIdx Pos, std::string_view & Data)
Definition at line 122 of file ASTReader.cpp.
References eat(), and nixt::DeserializeContext::STable.
Referenced by eatHookable().
eatExprWith()
nix::ExprWith nixt::ASTDeserializer::eatExprWith (nix::PosIdx Pos, std::string_view & Data)
Definition at line 277 of file ASTReader.cpp.
References eat(), and eatNonNullHookable().
Referenced by eatHookable().
eatHookable()
nix::Expr * nixt::ASTDeserializer::eatHookable (std::string_view & Data)
Definition at line 19 of file ASTReader.cpp.
References bc::eat(), eat(), eatExprAssert(), eatExprAttrs(), eatExprCall(), eatExprConcatStrings(), eatExprFloat(), eatExprIf(), eatExprInt(), eatExprLambnda(), eatExprLet(), eatExprList(), eatExprOpHasAttr(), eatExprOpNot(), eatExprPath(), eatExprSelect(), eatExprVar(), eatExprWith(), nixbc::EK_Assert, nixbc::EK_Attrs, nixbc::EK_Call, nixbc::EK_ConcatStrings, nixbc::EK_Float, nixbc::EK_If, nixbc::EK_Int, nixbc::EK_Lambda, nixbc::EK_Let, nixbc::EK_List, nixbc::EK_Null, nixbc::EK_OpHasAttr, nixbc::EK_OpNot, nixbc::EK_Path, nixbc::EK_Select, nixbc::EK_String, nixbc::EK_Var, nixbc::EK_With, HOOKEXPR, nixt::DeserializeContext::Origin, nixt::DeserializeContext::PTable, and nixt::PtrPool< T >::record().
Referenced by nixt::deserializeHookable(), eatAttrPath(), eatExprAttrs(), eatExprCall(), eatExprConcatStrings(), eatExprLambnda(), eatExprLet(), eatExprList(), eatExprOpHasAttr(), eatExprSelect(), and eatNonNullHookable().
eatNonNullHookable()
nix::Expr * nixt::ASTDeserializer::eatNonNullHookable (std::string_view & Data) inline
Definition at line 26 of file ASTReader.h.
References eat(), eatHookable(), nixt::PtrPool< T >::record(), and nixt::DeserializeContext::STable.
Referenced by eatExprAssert(), eatExprIf(), eatExprLambnda(), eatExprLet(), eatExprOpNot(), and eatExprWith().
eatPos()
nix::PosIdx nixt::ASTDeserializer::eatPos (std::string_view & Data)
Definition at line 104 of file ASTReader.cpp.
References eat(), nixt::DeserializeContext::Origin, and nixt::DeserializeContext::PTable.
Referenced by eatExprAttrs(), and eatExprLambnda().
eatSymbol()
nix::Symbol nixt::ASTDeserializer::eatSymbol (std::string_view & Data)
Definition at line 100 of file ASTReader.cpp.
References eat(), and nixt::DeserializeContext::STable.
Referenced by eatExprAttrs(), and eatExprLambnda().
The documentation for this class was generated from the following files:
ASTReader.h
ASTReader.cpp