nixd: nixt-decode.cpp File Reference
nixt-decode.cpp File Reference
#include "nixt/Deserialize.h"
#include "nixt/HookExpr.h"
#include "nixt/InitEval.h"
#include "nixt/PtrPool.h"
Functions
int main (int Argc, const char *Argv[])
Function Documentation
main()
int main (int Argc, const char * Argv[])
Definition at line 22 of file nixt-decode.cpp.
References nixt::deserializeHookable(), nixt::getDeserializeContext(), and nixt::initEval().